<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 15
        spacing: 15

        MDRaisedButton:
            text: "Option 1"
            font_size: '20sp'
            size_hint: (None, None)
            width: '200dp'
            height: '48dp'
            pos_hint: {'center_x': 0.5}
            on_release: root.option_1_selected(self)

        MDRaisedButton:
            text: "Option 2"
            font_size: '20sp'
            size_hint: (None, None)
            width: '200dp'
            height: '48dp'
            pos_hint: {'center_x': 0.5}
            on_release: root.option_2_selected(self)

        # Add any other UI elements for the main screen here
        # ...
