<SalaryCalcLayout>:
    orientation: 'vertical'
    padding: 15
    spacing: 15
    
    MDLabel:
        text: "Hey dani! Let's calculate your salary for today :)"
        font_style: 'H6'
        theme_text_color: 'Primary'
        halign: 'center'

    MDTextField:
        id: tip_amount
        hint_text: "Tip for today"
        font_size: '24sp'
        mode: "rectangle"
        size_hint: (None, None)
        width: '200dp'
        height: '48dp'
        multiline: False
        input_filter: 'int'
        helper_text: " "
        helper_text_mode: "on_error"
        pos_hint: {'center_x': 0.5}
        
    MDLabel:
        text: "Your base salary:"
        font_style: 'H6'
        theme_text_color: 'Primary'
        halign: 'center'
        
    MDTextField:
        id: base_salary
        hint_text: "Enter your base salary"
        font_size: '24sp'
        mode: "rectangle"
        size_hint: (None, None)
        width: '200dp'
        height: '48dp'
        multiline: False
        input_filter: 'int'
        text: "40"
        helper_text: " "
        helper_text_mode: "on_error"
        pos_hint: {'center_x': 0.5}
        
    MDRaisedButton:
        text: "Calculate"
        font_size: '20sp'
        size_hint: (None, None)
        width: '200dp'
        height: '48dp'
        pos_hint: {'center_x': 0.5}
        on_release: app.calculate(self)
        
    MDLabel:
        id: result_label
        font_style: 'H6'
        theme_text_color: 'Primary'
        halign: 'center'
        color: 0, 0.7, 1, 1
